package me.Plugins.SimpleFactions.Database;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class WarData {
    public int schemaVersion = 2;
    public int id;
    public String status;
    public String goal;
    public String warType;
    public String attackerLeaderId;
    public String defenderLeaderId;
    public String targetTitleId;
    public String subjectFactionId;
    public String relationTypeId;
    public Boolean internalWar;
    public String internalTopLiegeId;
    public String governmentLawId;
    public String leadershipLawId;
    public String targetSettlementId;
    public String movementId;
    public String civilWarHostFactionId;
    public String civilWarTempRebelFactionId;
    public Map<String, String> civilWarTransferredProvinces;
    public List<CivilWarVassalEndData> civilWarVassalEnds;
    public Integer civilWarHostOldCapitalId;
    public Integer civilWarRebelCapitalId;
    public String civilWarWantedLeaderName;
    public List<CivilWarMemberMoveData> civilWarMemberMoves;
    public String civilWarRebelMainGuildOwnName;
    public String civilWarMovedTitleId;
    public Integer objectiveProvinceId;
    public Integer campaignStartProvinceId;
    public List<Integer> campaignProvinces;
    public int cursorIndex;
    public Integer initiativeAttacker;
    public Integer initiativeDefender;
    public String initiativeHolder;
    public List<Integer> occupiedByAttacker;
    public List<Integer> occupiedByDefender;
    public List<Integer> lastBattleOccupied;
    public String campaignPhase;
    public String objectiveHeldBy;
    public boolean whitePeaceProposedByAttacker;
    public boolean whitePeaceProposedByDefender;
    public boolean forcedWhitePeaceByAttacker;
    public boolean forcedWhitePeaceByDefender;
    public Integer campaignBattlesFought;
    public List<ScheduledCampaignBattleData> campaignBattleSchedule;
    public Integer campaignScheduleIndex;
    public List<ScheduledCampaignBattleData> campaignCounterSchedule;
    public Integer campaignCounterScheduleIndex;
    public Map<String, String> fortControllers;
    public Map<String, String> wartimeInstallationOwners;
    public List<String> concededScheduleSlots;
    public Map<String, Integer> locationBattleCounts;
    public String battleSchedulePhase;
    public String battleDay;
    public String scheduledBattleAt;
    public Integer scheduledBattleHour;
    public Integer scheduledBattleProvinceId;
    public List<Integer> signupRemindersSent;
    public Map<String, List<Integer>> battleVotes;
    public Map<String, List<String>> battleInstallationPicks;
    public String battleInstallationPicksBattleDay;
    public Map<String, String> campaignRaidsUsed;
    public CampaignRaidData activeCampaignRaid;
    public Map<String, String> raidRepairLockUntil;
    public boolean autoresolveProposedByAttacker;
    public boolean autoresolveProposedByDefender;
    public Integer postponementsThisCycle;
    public boolean defenderChoiceResolved;
    public String initiativeHolderCoalition;
    public String pushTarget;
    public String postBattleChoicePhase;
    public String postBattleWinnerCoalition;
    public Boolean postBattleChoiceResolved;
    public String lastBattleOffensiveCoalition;
    public boolean holdPeaceProposalActive;
    public boolean forceQuorumNextClose;
    public String startedAt;
    public String endedAt;
    public String endReason;
    public SideData attackers;
    public SideData defenders;
    public List<CommitmentData> commitments;

    public WarData() {
        campaignProvinces = new ArrayList<>();
        occupiedByAttacker = new ArrayList<>();
        occupiedByDefender = new ArrayList<>();
        lastBattleOccupied = new ArrayList<>();
        battleVotes = new HashMap<>();
        battleInstallationPicks = new LinkedHashMap<>();
        campaignRaidsUsed = new LinkedHashMap<>();
        raidRepairLockUntil = new LinkedHashMap<>();
        locationBattleCounts = new HashMap<>();
        fortControllers = new HashMap<>();
        wartimeInstallationOwners = new LinkedHashMap<>();
        concededScheduleSlots = new ArrayList<>();
        campaignBattleSchedule = new ArrayList<>();
        campaignCounterSchedule = new ArrayList<>();
    }
}
